sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
  - '0.12'
  - '0.10'
before_install:
before_script:
  - rm -rf node_modules
  - npm install
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
